version: 2
sources:
  - name: open_exchange
    database: open-exchange-469422
    schema: rates_raw
    tables:
      - name: open_exchange_currency_raw
        description: "This is a source table for dbt."
        identifier: open-exchange-raw-currency
